version: '3'

services:
  backend:
    container_name: django
    build:
      context: ./api
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - mysql:mysql
      - redis:redis
    env_file:
      - envs/.djnago
    depends_on:
      - mysql
      - redis

  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/frontend/build

  nginx:
    image: nginx:latest
    build: ./nginx
    ports:
      - "80:80"
    links:
      - app:django
    volumes:
      - ./nginx:/nginx.conf:/etc/nginx/conf.MyUs/default.conf:ro
      - frontend_build:/var/www/frontend

  mysql:
    container_name: mysql
    build: ./mysql
    image: mysql:8.0.28
    env_file:
      - envs/.mysql
    ports:
      - "3307:3306"

  redis:
    container_name: redis:latest
    image: redis:5.0
    command: redis-server --requirepass A5656gu3y!redis
    ports:
      - "6380:6379"

depends_on:
  backend
  frontend

volumes:
  frontend_build:
