services:
  myus_backend:
    container_name: myus_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./myus:/code
    env_file:
      - ./myus/envs/django.env
    depends_on:
      - mysql
      - myus_redis
    ports:
      - "8056:8000"
    command: sh -c 'python manage.py runserver 0.0.0.0:8000 --settings config.settings.local'
    networks:
      - myus_network

  mysql:
    container_name: myus_mysql
    image: mysql:8.4
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./myus/envs/mysql.env
    ports:
      - "3356:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - myus_network

  myus_redis:
    container_name: myus_redis
    image: redis:7-alpine
    env_file:
      - ./myus/envs/redis.env
    ports:
      - "6356:6379"
    command: sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'
    networks:
      - myus_network

networks:
  myus_network:
    driver: bridge
