version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - mysql:mysql
      - redis:redis
    env_file:
      - envs/.aws
      - envs/.djnago
      - envs/.mysql
      - envs/.redis
    depends_on:
      - mysql
      - redis
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 | python manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/frontend/build

  nginx:
    image: nginx:latest
    build: ./nginx
    ports:
      - "80:80"
    links:
      - app:django
    volumes:
      - ./nginx:/nginx.conf:/etc/nginx/conf.MyUs/default.conf:ro
      - frontend_build:/var/www/frontend

  mysql:
    container_name: mysql
    build: ./mysql
    image: mysql:8.0.28
    env_file:
      - envs/.mysql
    ports:
      - "3305:3306"

  redis:
    container_name: redis:latest
    image: redis:5.0
    env_file:
      - envs/.redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass A5656gu3y!redis

depends_on:
  backend
  frontend

volumes:
  frontend_build:
