version: '3'

services:
  myus_backend:
    container_name: myus_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - ../log/dev/myus:/var/log/dev/
    env_file:
      - ./envs/django.env
    depends_on:
      - myus_mysql
      - myus_redis
    ports:
      - "8056:8000"
    command: sh -c 'python manage.py runserver 0.0.0.0:8056 --settings config.settings.local'
    # command: uwsgi --socket :8056 --module app.wsgi --py-autoreload 1

  # myus_frontend:
  #   container_name: myus_frontend
  #   restart: always
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - frontend_build:/frontend/build

  # myus_nginx:
  #   container_name: myus_nginx
  #   image: nginx:latest
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   links:
  #     - app:django
  #   volumes:
  #     - ./nginx:/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
  #     - ./static:/static

  myus_mysql:
    container_name: myus_mysql
    image: mysql/mysql-server:latest
    platform: linux/amd64
    # restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      # - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./envs/mysql.env
    ports:
      - "3356:3306"

  myus_redis:
    container_name: myus_redis
    image: redis:5.0
    env_file:
      - ./envs/redis.env
    ports:
      - "6356:6379"
    command: redis-server --requirepass redis1234
