# Generated by Django 4.1.1 on 2022-09-24 01:59

import apps.myus.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('nickname', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '001 User',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('type', models.CharField(blank=True, max_length=7)),
                ('type_id', models.BigIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '002 Access Log',
                'db_table': 'access_log',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('read', models.IntegerField(default=0)),
                ('thread', models.IntegerField(default=0)),
                ('joined', models.IntegerField(default=0)),
                ('period', models.DateField()),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '06 Chat',
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_name', models.CharField(max_length=30)),
                ('en_name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': '10 ハッシュタグ',
                'db_table': 'hashtag',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=apps.myus.models.images_video_upload)),
                ('video', models.FileField(upload_to=apps.myus.models.videos_video_upload)),
                ('convert', models.FileField(upload_to=apps.myus.models.videos_video_upload)),
                ('read', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(blank=True, to='myus.hashtag')),
                ('like', models.ManyToManyField(blank=True, related_name='video_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '01 Video',
                'db_table': 'video',
            },
            bases=(models.Model, apps.myus.models.MediaModel),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('danger', '高'), ('success', '普通'), ('info', '低')], max_length=10)),
                ('progress', models.CharField(choices=[('0', '未着手'), ('1', '進行中'), ('2', '完了')], max_length=10)),
                ('comment_num', models.IntegerField(default=0)),
                ('duedate', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '08 ToDo',
                'db_table': 'todo',
            },
        ),
        migrations.CreateModel(
            name='SearchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '09 検索タグ',
                'db_table': 'searchtag',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='../frontend/static/img/user_icon.png', null=True, upload_to=apps.myus.models.user_icon)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('0', '男性'), ('1', '女性'), ('2', '秘密')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号は090-1234-5678の形式で入力する必要があります。最大15桁まで入力できます', regex='\\d{2,4}-?\\d{2,4}-?\\d{3,4}')])),
                ('country_code', models.CharField(default='JP', max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('prefecture', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('building', models.CharField(blank=True, max_length=255)),
                ('introduction', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '001 profile',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myus.product')),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=apps.myus.models.images_picture_upload)),
                ('read', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(blank=True, to='myus.hashtag')),
                ('like', models.ManyToManyField(blank=True, related_name='picture_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '04 Picture',
                'db_table': 'picture',
            },
            bases=(models.Model, apps.myus.models.MediaModel),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_video', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('is_music', models.BooleanField(default=False)),
                ('is_picture', models.BooleanField(default=False)),
                ('is_blog', models.BooleanField(default=False)),
                ('is_chat', models.BooleanField(default=False)),
                ('is_collabo', models.BooleanField(default=False)),
                ('is_follow', models.BooleanField(default=True)),
                ('is_reply', models.BooleanField(default=True)),
                ('is_like', models.BooleanField(default=True)),
                ('is_views', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '001 通知設定',
                'db_table': 'notification_setting',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_no', models.IntegerField()),
                ('type_name', models.CharField(blank=True, max_length=7)),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.ManyToManyField(blank=True, related_name='confirmed', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('deleted', models.ManyToManyField(blank=True, related_name='deleted', to=settings.AUTH_USER_MODEL)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '12 通知確認',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='MyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, default='../frontend/static/img/MyUs_banner.png', null=True, upload_to=apps.myus.models.mypage_banner)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('follower_num', models.IntegerField(default=0, verbose_name='follower')),
                ('following_num', models.IntegerField(default=0, verbose_name='follow')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=10)),
                ('plan_date', models.DateTimeField(blank=True, null=True)),
                ('is_advertise', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '001 MyPage',
                'db_table': 'mypage',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('lyric', models.TextField(blank=True)),
                ('music', models.FileField(upload_to=apps.myus.models.musics_upload)),
                ('read', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('download', models.BooleanField(default=True)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(blank=True, to='myus.hashtag')),
                ('like', models.ManyToManyField(blank=True, related_name='music_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '03 Music',
                'db_table': 'music',
            },
            bases=(models.Model, apps.myus.models.MediaModel),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
                ('reply_num', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='myus.chat')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='myus.message')),
            ],
            options={
                'verbose_name_plural': '15 メッセージ',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=apps.myus.models.images_live_upload)),
                ('live', models.FileField(upload_to=apps.myus.models.videos_live_upload)),
                ('convert', models.FileField(upload_to=apps.myus.models.videos_live_upload)),
                ('read', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(blank=True, to='myus.hashtag')),
                ('like', models.ManyToManyField(blank=True, related_name='live_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '02 Live',
                'db_table': 'live',
            },
            bases=(models.Model, apps.myus.models.MediaModel),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '11 フォロー',
                'db_table': 'follow',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reply_num', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('like', models.ManyToManyField(blank=True, related_name='comment_like', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='myus.comment')),
            ],
            options={
                'verbose_name_plural': '14 コメント',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Collabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('read', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('period', models.DateField()),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(blank=True, to='myus.hashtag')),
                ('like', models.ManyToManyField(blank=True, related_name='collabo_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '07 Collabo',
                'db_table': 'collabo',
            },
            bases=(models.Model, apps.myus.models.MediaModel),
        ),
        migrations.AddField(
            model_name='chat',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='myus.hashtag'),
        ),
        migrations.AddField(
            model_name='chat',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='chat_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=apps.myus.models.images_blog_upload)),
                ('richtext', django_quill.fields.QuillField(blank=True)),
                ('read', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(blank=True, to='myus.hashtag')),
                ('like', models.ManyToManyField(blank=True, related_name='blog_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '05 Blog',
                'db_table': 'blog',
            },
            bases=(models.Model, apps.myus.models.MediaModel),
        ),
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=apps.myus.models.images_adver_upload)),
                ('video', models.FileField(upload_to=apps.myus.models.videos_adver_upload)),
                ('read', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('all', '全体'), ('one', '個別')], max_length=3)),
                ('period', models.DateField()),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '13 広告設定',
                'db_table': 'advertise',
            },
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['ip_address', 'type', 'type_id'], name='ip_address_type_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_from', 'user_to'], name='notification_from_to_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_no', 'object_id'], name='notification_type_object_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent'], name='message_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='follower_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='following_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'following'], name='follower_following_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comment_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='nickname_idx'),
        ),
    ]
