"""
Django settings for MyUs project.

Generated by 'django-admin startproject' using Django 5.2

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/ja/5.2/howto/deployment/checklist/

import os
from datetime import timedelta
from config.env import BASE_DIR, env


# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = env.debug

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.secret_key
ALLOWED_HOSTS = env.allowed_hosts

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# MySQL
DATABASES = {
    "default": {
        "ENGINE": env.mysql_engine,
        "NAME": env.mysql_database,
        "HOST": env.mysql_host,
        "PORT": env.mysql_port,
        "USER": env.mysql_user,
        "PASSWORD": env.mysql_password,
    }
}

# Top
INSTALLED_APPS = [
    "daphne"
]

# Application definition
INSTALLED_APPS += [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
]

# Add Application
INSTALLED_APPS += [
    "api.apps.ApiConfig",
    "corsheaders",
    "channels",
    "django_quill",
    "django_cleanup",
    "import_export",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "ninja.compatibility.files.fix_request_files_middleware",
]

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("JWT",),
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

TEMPLATES = [{
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [os.path.join(BASE_DIR, "templates")],
    "APP_DIRS": True,
    "OPTIONS": {
        "context_processors": [
            "django.template.context_processors.debug",
            "django.template.context_processors.request",
            "django.contrib.auth.context_processors.auth",
            "django.contrib.messages.context_processors.messages",
        ],
    },
}]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(env.redis_host, env.redis_port)],
        },
    },
}

ASGI_APPLICATION = "config.asgi.application"
WSGI_APPLICATION = "config.wsgi.application"
ROOT_URLCONF = "config.urls"

AUTH_USER_MODEL = "db.User"
AUTHENTICATION_BACKENDS = ["api.backends.MyBackend"]
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# CORS
CSRF_TRUSTED_ORIGINS = env.csrf_trusted_origins
CORS_ALLOWED_ORIGINS = env.cors_allowed_origins
CORS_ALLOW_METHODS = ("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS")

CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "access-control-allow-origin",
    "access-control-allow-credentials",
    "content-length",
    "content-disposition",
)

# humanize カンマ区切り値
NUMBER_GROUPING = 3

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
TIME_ZONE = "Asia/Tokyo"
LANGUAGE_CODE = "ja"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"),]
DOMAIN_URL = env.domain_url
ENCRYPT_KEY = env.encrypt_key
ENCRYPT_IV = env.encrypt_iv

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LOGIN_URL = "app:login"
LOGIN_REDIRECT_URL = "app:index"
LOGOUT_REDIRECT_URL = "app:login"

# File upload size limits
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024 * 1024  # 5GB (メモリ上でのファイルサイズ上限)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024 * 1024  # 5GB (POSTデータの上限)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240  # フォームフィールドの最大数

# Stripe API keys
STRIPE_SECRET_KEY = env.stripe_secret_key
STRIPE_PUBLIC_KEY = env.stripe_public_key

# Email
EMAIL_HOST = env.email_host
EMAIL_PORT = env.email_port
EMAIL_HOST_USER = env.email_host_user
EMAIL_HOST_PASSWORD = env.email_host_password
EMAIL_USE_TLS = True

# QUILL
QUILL_CONFIGS = {
    "default": {
        "theme": "snow",
        "modules": {
            "syntax": True,
            "toolbar": [
                [{"header": [1, 2, 3, 4, 5, 6, False]}],
                [{"color": []}, {"background": []}, {"align": []}],
                [{"indent": "-1"}, {"indent": "+1"}, {"list": "ordered"}, {"list": "bullet"}],
                ["bold", "italic", "underline", "strike", "formula", {"script": "super"}, {"script": "sub"}],
                ["code-block", "blockquote", "link", "image"],
            ]
        }
    }
}
