/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125RecommendRouteImport } from './routes/{-$locale}/recommend'
import { Route as Char123LocaleChar125AccountLoginRouteImport } from './routes/{-$locale}/account/login'
import { Route as Char123LocaleChar125ManageIndexRouteImport } from './routes/{-$locale}/manage/index'
import { Route as Char123LocaleChar125MenuChannelRouteImport } from './routes/{-$locale}/menu/channel'
import { Route as Char123LocaleChar125MenuFollowRouteImport } from './routes/{-$locale}/menu/follow'
import { Route as Char123LocaleChar125MenuFollowerRouteImport } from './routes/{-$locale}/menu/follower'
import { Route as Char123LocaleChar125MenuKnowledgeRouteImport } from './routes/{-$locale}/menu/knowledge'
import { Route as Char123LocaleChar125MenuUserpolicyRouteImport } from './routes/{-$locale}/menu/userpolicy'
import { Route as Char123LocaleChar125SettingNotificationRouteImport } from './routes/{-$locale}/setting/notification'
import { Route as Char123LocaleChar125UserpageUlidRouteImport } from './routes/{-$locale}/userpage/$ulid'
import { Route as Char123LocaleChar125AccountResetIndexRouteImport } from './routes/{-$locale}/account/reset/index'
import { Route as Char123LocaleChar125AccountResetConfirmRouteImport } from './routes/{-$locale}/account/reset/confirm'
import { Route as Char123LocaleChar125AccountResetDoneRouteImport } from './routes/{-$locale}/account/reset/done'
import { Route as Char123LocaleChar125AccountSignupIndexRouteImport } from './routes/{-$locale}/account/signup/index'
import { Route as Char123LocaleChar125AccountSignupEmailRouteImport } from './routes/{-$locale}/account/signup/email'
import { Route as Char123LocaleChar125AccountWithdrawalIndexRouteImport } from './routes/{-$locale}/account/withdrawal/index'
import { Route as Char123LocaleChar125AccountWithdrawalConfirmRouteImport } from './routes/{-$locale}/account/withdrawal/confirm'
import { Route as Char123LocaleChar125ManageAdvertiseIndexRouteImport } from './routes/{-$locale}/manage/advertise/index'
import { Route as Char123LocaleChar125ManageAdvertiseUlidRouteImport } from './routes/{-$locale}/manage/advertise/$ulid'
import { Route as Char123LocaleChar125ManageAdvertiseCreateRouteImport } from './routes/{-$locale}/manage/advertise/create'
import { Route as Char123LocaleChar125ManageBlogIndexRouteImport } from './routes/{-$locale}/manage/blog/index'
import { Route as Char123LocaleChar125ManageBlogUlidRouteImport } from './routes/{-$locale}/manage/blog/$ulid'
import { Route as Char123LocaleChar125ManageBlogCreateRouteImport } from './routes/{-$locale}/manage/blog/create'
import { Route as Char123LocaleChar125ManageChatIndexRouteImport } from './routes/{-$locale}/manage/chat/index'
import { Route as Char123LocaleChar125ManageChatUlidRouteImport } from './routes/{-$locale}/manage/chat/$ulid'
import { Route as Char123LocaleChar125ManageChatCreateRouteImport } from './routes/{-$locale}/manage/chat/create'
import { Route as Char123LocaleChar125ManageComicIndexRouteImport } from './routes/{-$locale}/manage/comic/index'
import { Route as Char123LocaleChar125ManageComicUlidRouteImport } from './routes/{-$locale}/manage/comic/$ulid'
import { Route as Char123LocaleChar125ManageComicCreateRouteImport } from './routes/{-$locale}/manage/comic/create'
import { Route as Char123LocaleChar125ManageMusicIndexRouteImport } from './routes/{-$locale}/manage/music/index'
import { Route as Char123LocaleChar125ManageMusicUlidRouteImport } from './routes/{-$locale}/manage/music/$ulid'
import { Route as Char123LocaleChar125ManageMusicCreateRouteImport } from './routes/{-$locale}/manage/music/create'
import { Route as Char123LocaleChar125ManagePictureIndexRouteImport } from './routes/{-$locale}/manage/picture/index'
import { Route as Char123LocaleChar125ManagePictureUlidRouteImport } from './routes/{-$locale}/manage/picture/$ulid'
import { Route as Char123LocaleChar125ManagePictureCreateRouteImport } from './routes/{-$locale}/manage/picture/create'
import { Route as Char123LocaleChar125ManageVideoIndexRouteImport } from './routes/{-$locale}/manage/video/index'
import { Route as Char123LocaleChar125ManageVideoUlidRouteImport } from './routes/{-$locale}/manage/video/$ulid'
import { Route as Char123LocaleChar125ManageVideoCreateRouteImport } from './routes/{-$locale}/manage/video/create'
import { Route as Char123LocaleChar125MediaBlogIndexRouteImport } from './routes/{-$locale}/media/blog/index'
import { Route as Char123LocaleChar125MediaBlogUlidRouteImport } from './routes/{-$locale}/media/blog/$ulid'
import { Route as Char123LocaleChar125MediaChatIndexRouteImport } from './routes/{-$locale}/media/chat/index'
import { Route as Char123LocaleChar125MediaChatUlidRouteImport } from './routes/{-$locale}/media/chat/$ulid'
import { Route as Char123LocaleChar125MediaComicIndexRouteImport } from './routes/{-$locale}/media/comic/index'
import { Route as Char123LocaleChar125MediaComicUlidRouteImport } from './routes/{-$locale}/media/comic/$ulid'
import { Route as Char123LocaleChar125MediaMusicIndexRouteImport } from './routes/{-$locale}/media/music/index'
import { Route as Char123LocaleChar125MediaMusicUlidRouteImport } from './routes/{-$locale}/media/music/$ulid'
import { Route as Char123LocaleChar125MediaPictureIndexRouteImport } from './routes/{-$locale}/media/picture/index'
import { Route as Char123LocaleChar125MediaPictureUlidRouteImport } from './routes/{-$locale}/media/picture/$ulid'
import { Route as Char123LocaleChar125MediaVideoIndexRouteImport } from './routes/{-$locale}/media/video/index'
import { Route as Char123LocaleChar125MediaVideoUlidRouteImport } from './routes/{-$locale}/media/video/$ulid'
import { Route as Char123LocaleChar125SettingMypageIndexRouteImport } from './routes/{-$locale}/setting/mypage/index'
import { Route as Char123LocaleChar125SettingMypageEditRouteImport } from './routes/{-$locale}/setting/mypage/edit'
import { Route as Char123LocaleChar125SettingPasswordChangeRouteImport } from './routes/{-$locale}/setting/password/change'
import { Route as Char123LocaleChar125SettingPasswordChangeDoneRouteImport } from './routes/{-$locale}/setting/password/change-done'
import { Route as Char123LocaleChar125SettingPaymentIndexRouteImport } from './routes/{-$locale}/setting/payment/index'
import { Route as Char123LocaleChar125SettingPaymentChangeRouteImport } from './routes/{-$locale}/setting/payment/change'
import { Route as Char123LocaleChar125SettingPaymentSuccessRouteImport } from './routes/{-$locale}/setting/payment/success'
import { Route as Char123LocaleChar125SettingProfileIndexRouteImport } from './routes/{-$locale}/setting/profile/index'
import { Route as Char123LocaleChar125SettingProfileEditRouteImport } from './routes/{-$locale}/setting/profile/edit'
import { Route as Char123LocaleChar125MediaChatUlidIndexRouteImport } from './routes/{-$locale}/media/chat/$ulid/index'
import { Route as Char123LocaleChar125SettingMypageChannelCreateRouteImport } from './routes/{-$locale}/setting/mypage/channel/create'
import { Route as Char123LocaleChar125MediaChatUlidThreadMessageUlidRouteImport } from './routes/{-$locale}/media/chat/$ulid/thread/$messageUlid'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125RecommendRoute =
  Char123LocaleChar125RecommendRouteImport.update({
    id: '/recommend',
    path: '/recommend',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccountLoginRoute =
  Char123LocaleChar125AccountLoginRouteImport.update({
    id: '/account/login',
    path: '/account/login',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageIndexRoute =
  Char123LocaleChar125ManageIndexRouteImport.update({
    id: '/manage/',
    path: '/manage/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MenuChannelRoute =
  Char123LocaleChar125MenuChannelRouteImport.update({
    id: '/menu/channel',
    path: '/menu/channel',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MenuFollowRoute =
  Char123LocaleChar125MenuFollowRouteImport.update({
    id: '/menu/follow',
    path: '/menu/follow',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MenuFollowerRoute =
  Char123LocaleChar125MenuFollowerRouteImport.update({
    id: '/menu/follower',
    path: '/menu/follower',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MenuKnowledgeRoute =
  Char123LocaleChar125MenuKnowledgeRouteImport.update({
    id: '/menu/knowledge',
    path: '/menu/knowledge',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MenuUserpolicyRoute =
  Char123LocaleChar125MenuUserpolicyRouteImport.update({
    id: '/menu/userpolicy',
    path: '/menu/userpolicy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingNotificationRoute =
  Char123LocaleChar125SettingNotificationRouteImport.update({
    id: '/setting/notification',
    path: '/setting/notification',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125UserpageUlidRoute =
  Char123LocaleChar125UserpageUlidRouteImport.update({
    id: '/userpage/$ulid',
    path: '/userpage/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccountResetIndexRoute =
  Char123LocaleChar125AccountResetIndexRouteImport.update({
    id: '/account/reset/',
    path: '/account/reset/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccountResetConfirmRoute =
  Char123LocaleChar125AccountResetConfirmRouteImport.update({
    id: '/account/reset/confirm',
    path: '/account/reset/confirm',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccountResetDoneRoute =
  Char123LocaleChar125AccountResetDoneRouteImport.update({
    id: '/account/reset/done',
    path: '/account/reset/done',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccountSignupIndexRoute =
  Char123LocaleChar125AccountSignupIndexRouteImport.update({
    id: '/account/signup/',
    path: '/account/signup/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccountSignupEmailRoute =
  Char123LocaleChar125AccountSignupEmailRouteImport.update({
    id: '/account/signup/email',
    path: '/account/signup/email',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccountWithdrawalIndexRoute =
  Char123LocaleChar125AccountWithdrawalIndexRouteImport.update({
    id: '/account/withdrawal/',
    path: '/account/withdrawal/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccountWithdrawalConfirmRoute =
  Char123LocaleChar125AccountWithdrawalConfirmRouteImport.update({
    id: '/account/withdrawal/confirm',
    path: '/account/withdrawal/confirm',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageAdvertiseIndexRoute =
  Char123LocaleChar125ManageAdvertiseIndexRouteImport.update({
    id: '/manage/advertise/',
    path: '/manage/advertise/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageAdvertiseUlidRoute =
  Char123LocaleChar125ManageAdvertiseUlidRouteImport.update({
    id: '/manage/advertise/$ulid',
    path: '/manage/advertise/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageAdvertiseCreateRoute =
  Char123LocaleChar125ManageAdvertiseCreateRouteImport.update({
    id: '/manage/advertise/create',
    path: '/manage/advertise/create',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageBlogIndexRoute =
  Char123LocaleChar125ManageBlogIndexRouteImport.update({
    id: '/manage/blog/',
    path: '/manage/blog/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageBlogUlidRoute =
  Char123LocaleChar125ManageBlogUlidRouteImport.update({
    id: '/manage/blog/$ulid',
    path: '/manage/blog/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageBlogCreateRoute =
  Char123LocaleChar125ManageBlogCreateRouteImport.update({
    id: '/manage/blog/create',
    path: '/manage/blog/create',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageChatIndexRoute =
  Char123LocaleChar125ManageChatIndexRouteImport.update({
    id: '/manage/chat/',
    path: '/manage/chat/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageChatUlidRoute =
  Char123LocaleChar125ManageChatUlidRouteImport.update({
    id: '/manage/chat/$ulid',
    path: '/manage/chat/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageChatCreateRoute =
  Char123LocaleChar125ManageChatCreateRouteImport.update({
    id: '/manage/chat/create',
    path: '/manage/chat/create',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageComicIndexRoute =
  Char123LocaleChar125ManageComicIndexRouteImport.update({
    id: '/manage/comic/',
    path: '/manage/comic/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageComicUlidRoute =
  Char123LocaleChar125ManageComicUlidRouteImport.update({
    id: '/manage/comic/$ulid',
    path: '/manage/comic/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageComicCreateRoute =
  Char123LocaleChar125ManageComicCreateRouteImport.update({
    id: '/manage/comic/create',
    path: '/manage/comic/create',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageMusicIndexRoute =
  Char123LocaleChar125ManageMusicIndexRouteImport.update({
    id: '/manage/music/',
    path: '/manage/music/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageMusicUlidRoute =
  Char123LocaleChar125ManageMusicUlidRouteImport.update({
    id: '/manage/music/$ulid',
    path: '/manage/music/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageMusicCreateRoute =
  Char123LocaleChar125ManageMusicCreateRouteImport.update({
    id: '/manage/music/create',
    path: '/manage/music/create',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManagePictureIndexRoute =
  Char123LocaleChar125ManagePictureIndexRouteImport.update({
    id: '/manage/picture/',
    path: '/manage/picture/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManagePictureUlidRoute =
  Char123LocaleChar125ManagePictureUlidRouteImport.update({
    id: '/manage/picture/$ulid',
    path: '/manage/picture/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManagePictureCreateRoute =
  Char123LocaleChar125ManagePictureCreateRouteImport.update({
    id: '/manage/picture/create',
    path: '/manage/picture/create',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageVideoIndexRoute =
  Char123LocaleChar125ManageVideoIndexRouteImport.update({
    id: '/manage/video/',
    path: '/manage/video/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageVideoUlidRoute =
  Char123LocaleChar125ManageVideoUlidRouteImport.update({
    id: '/manage/video/$ulid',
    path: '/manage/video/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ManageVideoCreateRoute =
  Char123LocaleChar125ManageVideoCreateRouteImport.update({
    id: '/manage/video/create',
    path: '/manage/video/create',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaBlogIndexRoute =
  Char123LocaleChar125MediaBlogIndexRouteImport.update({
    id: '/media/blog/',
    path: '/media/blog/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaBlogUlidRoute =
  Char123LocaleChar125MediaBlogUlidRouteImport.update({
    id: '/media/blog/$ulid',
    path: '/media/blog/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaChatIndexRoute =
  Char123LocaleChar125MediaChatIndexRouteImport.update({
    id: '/media/chat/',
    path: '/media/chat/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaChatUlidRoute =
  Char123LocaleChar125MediaChatUlidRouteImport.update({
    id: '/media/chat/$ulid',
    path: '/media/chat/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaComicIndexRoute =
  Char123LocaleChar125MediaComicIndexRouteImport.update({
    id: '/media/comic/',
    path: '/media/comic/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaComicUlidRoute =
  Char123LocaleChar125MediaComicUlidRouteImport.update({
    id: '/media/comic/$ulid',
    path: '/media/comic/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaMusicIndexRoute =
  Char123LocaleChar125MediaMusicIndexRouteImport.update({
    id: '/media/music/',
    path: '/media/music/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaMusicUlidRoute =
  Char123LocaleChar125MediaMusicUlidRouteImport.update({
    id: '/media/music/$ulid',
    path: '/media/music/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaPictureIndexRoute =
  Char123LocaleChar125MediaPictureIndexRouteImport.update({
    id: '/media/picture/',
    path: '/media/picture/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaPictureUlidRoute =
  Char123LocaleChar125MediaPictureUlidRouteImport.update({
    id: '/media/picture/$ulid',
    path: '/media/picture/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaVideoIndexRoute =
  Char123LocaleChar125MediaVideoIndexRouteImport.update({
    id: '/media/video/',
    path: '/media/video/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaVideoUlidRoute =
  Char123LocaleChar125MediaVideoUlidRouteImport.update({
    id: '/media/video/$ulid',
    path: '/media/video/$ulid',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingMypageIndexRoute =
  Char123LocaleChar125SettingMypageIndexRouteImport.update({
    id: '/setting/mypage/',
    path: '/setting/mypage/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingMypageEditRoute =
  Char123LocaleChar125SettingMypageEditRouteImport.update({
    id: '/setting/mypage/edit',
    path: '/setting/mypage/edit',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingPasswordChangeRoute =
  Char123LocaleChar125SettingPasswordChangeRouteImport.update({
    id: '/setting/password/change',
    path: '/setting/password/change',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingPasswordChangeDoneRoute =
  Char123LocaleChar125SettingPasswordChangeDoneRouteImport.update({
    id: '/setting/password/change-done',
    path: '/setting/password/change-done',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingPaymentIndexRoute =
  Char123LocaleChar125SettingPaymentIndexRouteImport.update({
    id: '/setting/payment/',
    path: '/setting/payment/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingPaymentChangeRoute =
  Char123LocaleChar125SettingPaymentChangeRouteImport.update({
    id: '/setting/payment/change',
    path: '/setting/payment/change',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingPaymentSuccessRoute =
  Char123LocaleChar125SettingPaymentSuccessRouteImport.update({
    id: '/setting/payment/success',
    path: '/setting/payment/success',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingProfileIndexRoute =
  Char123LocaleChar125SettingProfileIndexRouteImport.update({
    id: '/setting/profile/',
    path: '/setting/profile/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SettingProfileEditRoute =
  Char123LocaleChar125SettingProfileEditRouteImport.update({
    id: '/setting/profile/edit',
    path: '/setting/profile/edit',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaChatUlidIndexRoute =
  Char123LocaleChar125MediaChatUlidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125MediaChatUlidRoute,
  } as any)
const Char123LocaleChar125SettingMypageChannelCreateRoute =
  Char123LocaleChar125SettingMypageChannelCreateRouteImport.update({
    id: '/setting/mypage/channel/create',
    path: '/setting/mypage/channel/create',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MediaChatUlidThreadMessageUlidRoute =
  Char123LocaleChar125MediaChatUlidThreadMessageUlidRouteImport.update({
    id: '/thread/$messageUlid',
    path: '/thread/$messageUlid',
    getParentRoute: () => Char123LocaleChar125MediaChatUlidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/recommend': typeof Char123LocaleChar125RecommendRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/account/login': typeof Char123LocaleChar125AccountLoginRoute
  '/{-$locale}/menu/channel': typeof Char123LocaleChar125MenuChannelRoute
  '/{-$locale}/menu/follow': typeof Char123LocaleChar125MenuFollowRoute
  '/{-$locale}/menu/follower': typeof Char123LocaleChar125MenuFollowerRoute
  '/{-$locale}/menu/knowledge': typeof Char123LocaleChar125MenuKnowledgeRoute
  '/{-$locale}/menu/userpolicy': typeof Char123LocaleChar125MenuUserpolicyRoute
  '/{-$locale}/setting/notification': typeof Char123LocaleChar125SettingNotificationRoute
  '/{-$locale}/userpage/$ulid': typeof Char123LocaleChar125UserpageUlidRoute
  '/{-$locale}/manage/': typeof Char123LocaleChar125ManageIndexRoute
  '/{-$locale}/account/reset/confirm': typeof Char123LocaleChar125AccountResetConfirmRoute
  '/{-$locale}/account/reset/done': typeof Char123LocaleChar125AccountResetDoneRoute
  '/{-$locale}/account/signup/email': typeof Char123LocaleChar125AccountSignupEmailRoute
  '/{-$locale}/account/withdrawal/confirm': typeof Char123LocaleChar125AccountWithdrawalConfirmRoute
  '/{-$locale}/manage/advertise/$ulid': typeof Char123LocaleChar125ManageAdvertiseUlidRoute
  '/{-$locale}/manage/advertise/create': typeof Char123LocaleChar125ManageAdvertiseCreateRoute
  '/{-$locale}/manage/blog/$ulid': typeof Char123LocaleChar125ManageBlogUlidRoute
  '/{-$locale}/manage/blog/create': typeof Char123LocaleChar125ManageBlogCreateRoute
  '/{-$locale}/manage/chat/$ulid': typeof Char123LocaleChar125ManageChatUlidRoute
  '/{-$locale}/manage/chat/create': typeof Char123LocaleChar125ManageChatCreateRoute
  '/{-$locale}/manage/comic/$ulid': typeof Char123LocaleChar125ManageComicUlidRoute
  '/{-$locale}/manage/comic/create': typeof Char123LocaleChar125ManageComicCreateRoute
  '/{-$locale}/manage/music/$ulid': typeof Char123LocaleChar125ManageMusicUlidRoute
  '/{-$locale}/manage/music/create': typeof Char123LocaleChar125ManageMusicCreateRoute
  '/{-$locale}/manage/picture/$ulid': typeof Char123LocaleChar125ManagePictureUlidRoute
  '/{-$locale}/manage/picture/create': typeof Char123LocaleChar125ManagePictureCreateRoute
  '/{-$locale}/manage/video/$ulid': typeof Char123LocaleChar125ManageVideoUlidRoute
  '/{-$locale}/manage/video/create': typeof Char123LocaleChar125ManageVideoCreateRoute
  '/{-$locale}/media/blog/$ulid': typeof Char123LocaleChar125MediaBlogUlidRoute
  '/{-$locale}/media/chat/$ulid': typeof Char123LocaleChar125MediaChatUlidRouteWithChildren
  '/{-$locale}/media/comic/$ulid': typeof Char123LocaleChar125MediaComicUlidRoute
  '/{-$locale}/media/music/$ulid': typeof Char123LocaleChar125MediaMusicUlidRoute
  '/{-$locale}/media/picture/$ulid': typeof Char123LocaleChar125MediaPictureUlidRoute
  '/{-$locale}/media/video/$ulid': typeof Char123LocaleChar125MediaVideoUlidRoute
  '/{-$locale}/setting/mypage/edit': typeof Char123LocaleChar125SettingMypageEditRoute
  '/{-$locale}/setting/password/change': typeof Char123LocaleChar125SettingPasswordChangeRoute
  '/{-$locale}/setting/password/change-done': typeof Char123LocaleChar125SettingPasswordChangeDoneRoute
  '/{-$locale}/setting/payment/change': typeof Char123LocaleChar125SettingPaymentChangeRoute
  '/{-$locale}/setting/payment/success': typeof Char123LocaleChar125SettingPaymentSuccessRoute
  '/{-$locale}/setting/profile/edit': typeof Char123LocaleChar125SettingProfileEditRoute
  '/{-$locale}/account/reset/': typeof Char123LocaleChar125AccountResetIndexRoute
  '/{-$locale}/account/signup/': typeof Char123LocaleChar125AccountSignupIndexRoute
  '/{-$locale}/account/withdrawal/': typeof Char123LocaleChar125AccountWithdrawalIndexRoute
  '/{-$locale}/manage/advertise/': typeof Char123LocaleChar125ManageAdvertiseIndexRoute
  '/{-$locale}/manage/blog/': typeof Char123LocaleChar125ManageBlogIndexRoute
  '/{-$locale}/manage/chat/': typeof Char123LocaleChar125ManageChatIndexRoute
  '/{-$locale}/manage/comic/': typeof Char123LocaleChar125ManageComicIndexRoute
  '/{-$locale}/manage/music/': typeof Char123LocaleChar125ManageMusicIndexRoute
  '/{-$locale}/manage/picture/': typeof Char123LocaleChar125ManagePictureIndexRoute
  '/{-$locale}/manage/video/': typeof Char123LocaleChar125ManageVideoIndexRoute
  '/{-$locale}/media/blog/': typeof Char123LocaleChar125MediaBlogIndexRoute
  '/{-$locale}/media/chat/': typeof Char123LocaleChar125MediaChatIndexRoute
  '/{-$locale}/media/comic/': typeof Char123LocaleChar125MediaComicIndexRoute
  '/{-$locale}/media/music/': typeof Char123LocaleChar125MediaMusicIndexRoute
  '/{-$locale}/media/picture/': typeof Char123LocaleChar125MediaPictureIndexRoute
  '/{-$locale}/media/video/': typeof Char123LocaleChar125MediaVideoIndexRoute
  '/{-$locale}/setting/mypage/': typeof Char123LocaleChar125SettingMypageIndexRoute
  '/{-$locale}/setting/payment/': typeof Char123LocaleChar125SettingPaymentIndexRoute
  '/{-$locale}/setting/profile/': typeof Char123LocaleChar125SettingProfileIndexRoute
  '/{-$locale}/setting/mypage/channel/create': typeof Char123LocaleChar125SettingMypageChannelCreateRoute
  '/{-$locale}/media/chat/$ulid/': typeof Char123LocaleChar125MediaChatUlidIndexRoute
  '/{-$locale}/media/chat/$ulid/thread/$messageUlid': typeof Char123LocaleChar125MediaChatUlidThreadMessageUlidRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/recommend': typeof Char123LocaleChar125RecommendRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/account/login': typeof Char123LocaleChar125AccountLoginRoute
  '/{-$locale}/menu/channel': typeof Char123LocaleChar125MenuChannelRoute
  '/{-$locale}/menu/follow': typeof Char123LocaleChar125MenuFollowRoute
  '/{-$locale}/menu/follower': typeof Char123LocaleChar125MenuFollowerRoute
  '/{-$locale}/menu/knowledge': typeof Char123LocaleChar125MenuKnowledgeRoute
  '/{-$locale}/menu/userpolicy': typeof Char123LocaleChar125MenuUserpolicyRoute
  '/{-$locale}/setting/notification': typeof Char123LocaleChar125SettingNotificationRoute
  '/{-$locale}/userpage/$ulid': typeof Char123LocaleChar125UserpageUlidRoute
  '/{-$locale}/manage': typeof Char123LocaleChar125ManageIndexRoute
  '/{-$locale}/account/reset/confirm': typeof Char123LocaleChar125AccountResetConfirmRoute
  '/{-$locale}/account/reset/done': typeof Char123LocaleChar125AccountResetDoneRoute
  '/{-$locale}/account/signup/email': typeof Char123LocaleChar125AccountSignupEmailRoute
  '/{-$locale}/account/withdrawal/confirm': typeof Char123LocaleChar125AccountWithdrawalConfirmRoute
  '/{-$locale}/manage/advertise/$ulid': typeof Char123LocaleChar125ManageAdvertiseUlidRoute
  '/{-$locale}/manage/advertise/create': typeof Char123LocaleChar125ManageAdvertiseCreateRoute
  '/{-$locale}/manage/blog/$ulid': typeof Char123LocaleChar125ManageBlogUlidRoute
  '/{-$locale}/manage/blog/create': typeof Char123LocaleChar125ManageBlogCreateRoute
  '/{-$locale}/manage/chat/$ulid': typeof Char123LocaleChar125ManageChatUlidRoute
  '/{-$locale}/manage/chat/create': typeof Char123LocaleChar125ManageChatCreateRoute
  '/{-$locale}/manage/comic/$ulid': typeof Char123LocaleChar125ManageComicUlidRoute
  '/{-$locale}/manage/comic/create': typeof Char123LocaleChar125ManageComicCreateRoute
  '/{-$locale}/manage/music/$ulid': typeof Char123LocaleChar125ManageMusicUlidRoute
  '/{-$locale}/manage/music/create': typeof Char123LocaleChar125ManageMusicCreateRoute
  '/{-$locale}/manage/picture/$ulid': typeof Char123LocaleChar125ManagePictureUlidRoute
  '/{-$locale}/manage/picture/create': typeof Char123LocaleChar125ManagePictureCreateRoute
  '/{-$locale}/manage/video/$ulid': typeof Char123LocaleChar125ManageVideoUlidRoute
  '/{-$locale}/manage/video/create': typeof Char123LocaleChar125ManageVideoCreateRoute
  '/{-$locale}/media/blog/$ulid': typeof Char123LocaleChar125MediaBlogUlidRoute
  '/{-$locale}/media/comic/$ulid': typeof Char123LocaleChar125MediaComicUlidRoute
  '/{-$locale}/media/music/$ulid': typeof Char123LocaleChar125MediaMusicUlidRoute
  '/{-$locale}/media/picture/$ulid': typeof Char123LocaleChar125MediaPictureUlidRoute
  '/{-$locale}/media/video/$ulid': typeof Char123LocaleChar125MediaVideoUlidRoute
  '/{-$locale}/setting/mypage/edit': typeof Char123LocaleChar125SettingMypageEditRoute
  '/{-$locale}/setting/password/change': typeof Char123LocaleChar125SettingPasswordChangeRoute
  '/{-$locale}/setting/password/change-done': typeof Char123LocaleChar125SettingPasswordChangeDoneRoute
  '/{-$locale}/setting/payment/change': typeof Char123LocaleChar125SettingPaymentChangeRoute
  '/{-$locale}/setting/payment/success': typeof Char123LocaleChar125SettingPaymentSuccessRoute
  '/{-$locale}/setting/profile/edit': typeof Char123LocaleChar125SettingProfileEditRoute
  '/{-$locale}/account/reset': typeof Char123LocaleChar125AccountResetIndexRoute
  '/{-$locale}/account/signup': typeof Char123LocaleChar125AccountSignupIndexRoute
  '/{-$locale}/account/withdrawal': typeof Char123LocaleChar125AccountWithdrawalIndexRoute
  '/{-$locale}/manage/advertise': typeof Char123LocaleChar125ManageAdvertiseIndexRoute
  '/{-$locale}/manage/blog': typeof Char123LocaleChar125ManageBlogIndexRoute
  '/{-$locale}/manage/chat': typeof Char123LocaleChar125ManageChatIndexRoute
  '/{-$locale}/manage/comic': typeof Char123LocaleChar125ManageComicIndexRoute
  '/{-$locale}/manage/music': typeof Char123LocaleChar125ManageMusicIndexRoute
  '/{-$locale}/manage/picture': typeof Char123LocaleChar125ManagePictureIndexRoute
  '/{-$locale}/manage/video': typeof Char123LocaleChar125ManageVideoIndexRoute
  '/{-$locale}/media/blog': typeof Char123LocaleChar125MediaBlogIndexRoute
  '/{-$locale}/media/chat': typeof Char123LocaleChar125MediaChatIndexRoute
  '/{-$locale}/media/comic': typeof Char123LocaleChar125MediaComicIndexRoute
  '/{-$locale}/media/music': typeof Char123LocaleChar125MediaMusicIndexRoute
  '/{-$locale}/media/picture': typeof Char123LocaleChar125MediaPictureIndexRoute
  '/{-$locale}/media/video': typeof Char123LocaleChar125MediaVideoIndexRoute
  '/{-$locale}/setting/mypage': typeof Char123LocaleChar125SettingMypageIndexRoute
  '/{-$locale}/setting/payment': typeof Char123LocaleChar125SettingPaymentIndexRoute
  '/{-$locale}/setting/profile': typeof Char123LocaleChar125SettingProfileIndexRoute
  '/{-$locale}/setting/mypage/channel/create': typeof Char123LocaleChar125SettingMypageChannelCreateRoute
  '/{-$locale}/media/chat/$ulid': typeof Char123LocaleChar125MediaChatUlidIndexRoute
  '/{-$locale}/media/chat/$ulid/thread/$messageUlid': typeof Char123LocaleChar125MediaChatUlidThreadMessageUlidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/recommend': typeof Char123LocaleChar125RecommendRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/account/login': typeof Char123LocaleChar125AccountLoginRoute
  '/{-$locale}/menu/channel': typeof Char123LocaleChar125MenuChannelRoute
  '/{-$locale}/menu/follow': typeof Char123LocaleChar125MenuFollowRoute
  '/{-$locale}/menu/follower': typeof Char123LocaleChar125MenuFollowerRoute
  '/{-$locale}/menu/knowledge': typeof Char123LocaleChar125MenuKnowledgeRoute
  '/{-$locale}/menu/userpolicy': typeof Char123LocaleChar125MenuUserpolicyRoute
  '/{-$locale}/setting/notification': typeof Char123LocaleChar125SettingNotificationRoute
  '/{-$locale}/userpage/$ulid': typeof Char123LocaleChar125UserpageUlidRoute
  '/{-$locale}/manage/': typeof Char123LocaleChar125ManageIndexRoute
  '/{-$locale}/account/reset/confirm': typeof Char123LocaleChar125AccountResetConfirmRoute
  '/{-$locale}/account/reset/done': typeof Char123LocaleChar125AccountResetDoneRoute
  '/{-$locale}/account/signup/email': typeof Char123LocaleChar125AccountSignupEmailRoute
  '/{-$locale}/account/withdrawal/confirm': typeof Char123LocaleChar125AccountWithdrawalConfirmRoute
  '/{-$locale}/manage/advertise/$ulid': typeof Char123LocaleChar125ManageAdvertiseUlidRoute
  '/{-$locale}/manage/advertise/create': typeof Char123LocaleChar125ManageAdvertiseCreateRoute
  '/{-$locale}/manage/blog/$ulid': typeof Char123LocaleChar125ManageBlogUlidRoute
  '/{-$locale}/manage/blog/create': typeof Char123LocaleChar125ManageBlogCreateRoute
  '/{-$locale}/manage/chat/$ulid': typeof Char123LocaleChar125ManageChatUlidRoute
  '/{-$locale}/manage/chat/create': typeof Char123LocaleChar125ManageChatCreateRoute
  '/{-$locale}/manage/comic/$ulid': typeof Char123LocaleChar125ManageComicUlidRoute
  '/{-$locale}/manage/comic/create': typeof Char123LocaleChar125ManageComicCreateRoute
  '/{-$locale}/manage/music/$ulid': typeof Char123LocaleChar125ManageMusicUlidRoute
  '/{-$locale}/manage/music/create': typeof Char123LocaleChar125ManageMusicCreateRoute
  '/{-$locale}/manage/picture/$ulid': typeof Char123LocaleChar125ManagePictureUlidRoute
  '/{-$locale}/manage/picture/create': typeof Char123LocaleChar125ManagePictureCreateRoute
  '/{-$locale}/manage/video/$ulid': typeof Char123LocaleChar125ManageVideoUlidRoute
  '/{-$locale}/manage/video/create': typeof Char123LocaleChar125ManageVideoCreateRoute
  '/{-$locale}/media/blog/$ulid': typeof Char123LocaleChar125MediaBlogUlidRoute
  '/{-$locale}/media/chat/$ulid': typeof Char123LocaleChar125MediaChatUlidRouteWithChildren
  '/{-$locale}/media/comic/$ulid': typeof Char123LocaleChar125MediaComicUlidRoute
  '/{-$locale}/media/music/$ulid': typeof Char123LocaleChar125MediaMusicUlidRoute
  '/{-$locale}/media/picture/$ulid': typeof Char123LocaleChar125MediaPictureUlidRoute
  '/{-$locale}/media/video/$ulid': typeof Char123LocaleChar125MediaVideoUlidRoute
  '/{-$locale}/setting/mypage/edit': typeof Char123LocaleChar125SettingMypageEditRoute
  '/{-$locale}/setting/password/change': typeof Char123LocaleChar125SettingPasswordChangeRoute
  '/{-$locale}/setting/password/change-done': typeof Char123LocaleChar125SettingPasswordChangeDoneRoute
  '/{-$locale}/setting/payment/change': typeof Char123LocaleChar125SettingPaymentChangeRoute
  '/{-$locale}/setting/payment/success': typeof Char123LocaleChar125SettingPaymentSuccessRoute
  '/{-$locale}/setting/profile/edit': typeof Char123LocaleChar125SettingProfileEditRoute
  '/{-$locale}/account/reset/': typeof Char123LocaleChar125AccountResetIndexRoute
  '/{-$locale}/account/signup/': typeof Char123LocaleChar125AccountSignupIndexRoute
  '/{-$locale}/account/withdrawal/': typeof Char123LocaleChar125AccountWithdrawalIndexRoute
  '/{-$locale}/manage/advertise/': typeof Char123LocaleChar125ManageAdvertiseIndexRoute
  '/{-$locale}/manage/blog/': typeof Char123LocaleChar125ManageBlogIndexRoute
  '/{-$locale}/manage/chat/': typeof Char123LocaleChar125ManageChatIndexRoute
  '/{-$locale}/manage/comic/': typeof Char123LocaleChar125ManageComicIndexRoute
  '/{-$locale}/manage/music/': typeof Char123LocaleChar125ManageMusicIndexRoute
  '/{-$locale}/manage/picture/': typeof Char123LocaleChar125ManagePictureIndexRoute
  '/{-$locale}/manage/video/': typeof Char123LocaleChar125ManageVideoIndexRoute
  '/{-$locale}/media/blog/': typeof Char123LocaleChar125MediaBlogIndexRoute
  '/{-$locale}/media/chat/': typeof Char123LocaleChar125MediaChatIndexRoute
  '/{-$locale}/media/comic/': typeof Char123LocaleChar125MediaComicIndexRoute
  '/{-$locale}/media/music/': typeof Char123LocaleChar125MediaMusicIndexRoute
  '/{-$locale}/media/picture/': typeof Char123LocaleChar125MediaPictureIndexRoute
  '/{-$locale}/media/video/': typeof Char123LocaleChar125MediaVideoIndexRoute
  '/{-$locale}/setting/mypage/': typeof Char123LocaleChar125SettingMypageIndexRoute
  '/{-$locale}/setting/payment/': typeof Char123LocaleChar125SettingPaymentIndexRoute
  '/{-$locale}/setting/profile/': typeof Char123LocaleChar125SettingProfileIndexRoute
  '/{-$locale}/setting/mypage/channel/create': typeof Char123LocaleChar125SettingMypageChannelCreateRoute
  '/{-$locale}/media/chat/$ulid/': typeof Char123LocaleChar125MediaChatUlidIndexRoute
  '/{-$locale}/media/chat/$ulid/thread/$messageUlid': typeof Char123LocaleChar125MediaChatUlidThreadMessageUlidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/recommend'
    | '/{-$locale}/'
    | '/{-$locale}/account/login'
    | '/{-$locale}/menu/channel'
    | '/{-$locale}/menu/follow'
    | '/{-$locale}/menu/follower'
    | '/{-$locale}/menu/knowledge'
    | '/{-$locale}/menu/userpolicy'
    | '/{-$locale}/setting/notification'
    | '/{-$locale}/userpage/$ulid'
    | '/{-$locale}/manage/'
    | '/{-$locale}/account/reset/confirm'
    | '/{-$locale}/account/reset/done'
    | '/{-$locale}/account/signup/email'
    | '/{-$locale}/account/withdrawal/confirm'
    | '/{-$locale}/manage/advertise/$ulid'
    | '/{-$locale}/manage/advertise/create'
    | '/{-$locale}/manage/blog/$ulid'
    | '/{-$locale}/manage/blog/create'
    | '/{-$locale}/manage/chat/$ulid'
    | '/{-$locale}/manage/chat/create'
    | '/{-$locale}/manage/comic/$ulid'
    | '/{-$locale}/manage/comic/create'
    | '/{-$locale}/manage/music/$ulid'
    | '/{-$locale}/manage/music/create'
    | '/{-$locale}/manage/picture/$ulid'
    | '/{-$locale}/manage/picture/create'
    | '/{-$locale}/manage/video/$ulid'
    | '/{-$locale}/manage/video/create'
    | '/{-$locale}/media/blog/$ulid'
    | '/{-$locale}/media/chat/$ulid'
    | '/{-$locale}/media/comic/$ulid'
    | '/{-$locale}/media/music/$ulid'
    | '/{-$locale}/media/picture/$ulid'
    | '/{-$locale}/media/video/$ulid'
    | '/{-$locale}/setting/mypage/edit'
    | '/{-$locale}/setting/password/change'
    | '/{-$locale}/setting/password/change-done'
    | '/{-$locale}/setting/payment/change'
    | '/{-$locale}/setting/payment/success'
    | '/{-$locale}/setting/profile/edit'
    | '/{-$locale}/account/reset/'
    | '/{-$locale}/account/signup/'
    | '/{-$locale}/account/withdrawal/'
    | '/{-$locale}/manage/advertise/'
    | '/{-$locale}/manage/blog/'
    | '/{-$locale}/manage/chat/'
    | '/{-$locale}/manage/comic/'
    | '/{-$locale}/manage/music/'
    | '/{-$locale}/manage/picture/'
    | '/{-$locale}/manage/video/'
    | '/{-$locale}/media/blog/'
    | '/{-$locale}/media/chat/'
    | '/{-$locale}/media/comic/'
    | '/{-$locale}/media/music/'
    | '/{-$locale}/media/picture/'
    | '/{-$locale}/media/video/'
    | '/{-$locale}/setting/mypage/'
    | '/{-$locale}/setting/payment/'
    | '/{-$locale}/setting/profile/'
    | '/{-$locale}/setting/mypage/channel/create'
    | '/{-$locale}/media/chat/$ulid/'
    | '/{-$locale}/media/chat/$ulid/thread/$messageUlid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/recommend'
    | '/{-$locale}'
    | '/{-$locale}/account/login'
    | '/{-$locale}/menu/channel'
    | '/{-$locale}/menu/follow'
    | '/{-$locale}/menu/follower'
    | '/{-$locale}/menu/knowledge'
    | '/{-$locale}/menu/userpolicy'
    | '/{-$locale}/setting/notification'
    | '/{-$locale}/userpage/$ulid'
    | '/{-$locale}/manage'
    | '/{-$locale}/account/reset/confirm'
    | '/{-$locale}/account/reset/done'
    | '/{-$locale}/account/signup/email'
    | '/{-$locale}/account/withdrawal/confirm'
    | '/{-$locale}/manage/advertise/$ulid'
    | '/{-$locale}/manage/advertise/create'
    | '/{-$locale}/manage/blog/$ulid'
    | '/{-$locale}/manage/blog/create'
    | '/{-$locale}/manage/chat/$ulid'
    | '/{-$locale}/manage/chat/create'
    | '/{-$locale}/manage/comic/$ulid'
    | '/{-$locale}/manage/comic/create'
    | '/{-$locale}/manage/music/$ulid'
    | '/{-$locale}/manage/music/create'
    | '/{-$locale}/manage/picture/$ulid'
    | '/{-$locale}/manage/picture/create'
    | '/{-$locale}/manage/video/$ulid'
    | '/{-$locale}/manage/video/create'
    | '/{-$locale}/media/blog/$ulid'
    | '/{-$locale}/media/comic/$ulid'
    | '/{-$locale}/media/music/$ulid'
    | '/{-$locale}/media/picture/$ulid'
    | '/{-$locale}/media/video/$ulid'
    | '/{-$locale}/setting/mypage/edit'
    | '/{-$locale}/setting/password/change'
    | '/{-$locale}/setting/password/change-done'
    | '/{-$locale}/setting/payment/change'
    | '/{-$locale}/setting/payment/success'
    | '/{-$locale}/setting/profile/edit'
    | '/{-$locale}/account/reset'
    | '/{-$locale}/account/signup'
    | '/{-$locale}/account/withdrawal'
    | '/{-$locale}/manage/advertise'
    | '/{-$locale}/manage/blog'
    | '/{-$locale}/manage/chat'
    | '/{-$locale}/manage/comic'
    | '/{-$locale}/manage/music'
    | '/{-$locale}/manage/picture'
    | '/{-$locale}/manage/video'
    | '/{-$locale}/media/blog'
    | '/{-$locale}/media/chat'
    | '/{-$locale}/media/comic'
    | '/{-$locale}/media/music'
    | '/{-$locale}/media/picture'
    | '/{-$locale}/media/video'
    | '/{-$locale}/setting/mypage'
    | '/{-$locale}/setting/payment'
    | '/{-$locale}/setting/profile'
    | '/{-$locale}/setting/mypage/channel/create'
    | '/{-$locale}/media/chat/$ulid'
    | '/{-$locale}/media/chat/$ulid/thread/$messageUlid'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/recommend'
    | '/{-$locale}/'
    | '/{-$locale}/account/login'
    | '/{-$locale}/menu/channel'
    | '/{-$locale}/menu/follow'
    | '/{-$locale}/menu/follower'
    | '/{-$locale}/menu/knowledge'
    | '/{-$locale}/menu/userpolicy'
    | '/{-$locale}/setting/notification'
    | '/{-$locale}/userpage/$ulid'
    | '/{-$locale}/manage/'
    | '/{-$locale}/account/reset/confirm'
    | '/{-$locale}/account/reset/done'
    | '/{-$locale}/account/signup/email'
    | '/{-$locale}/account/withdrawal/confirm'
    | '/{-$locale}/manage/advertise/$ulid'
    | '/{-$locale}/manage/advertise/create'
    | '/{-$locale}/manage/blog/$ulid'
    | '/{-$locale}/manage/blog/create'
    | '/{-$locale}/manage/chat/$ulid'
    | '/{-$locale}/manage/chat/create'
    | '/{-$locale}/manage/comic/$ulid'
    | '/{-$locale}/manage/comic/create'
    | '/{-$locale}/manage/music/$ulid'
    | '/{-$locale}/manage/music/create'
    | '/{-$locale}/manage/picture/$ulid'
    | '/{-$locale}/manage/picture/create'
    | '/{-$locale}/manage/video/$ulid'
    | '/{-$locale}/manage/video/create'
    | '/{-$locale}/media/blog/$ulid'
    | '/{-$locale}/media/chat/$ulid'
    | '/{-$locale}/media/comic/$ulid'
    | '/{-$locale}/media/music/$ulid'
    | '/{-$locale}/media/picture/$ulid'
    | '/{-$locale}/media/video/$ulid'
    | '/{-$locale}/setting/mypage/edit'
    | '/{-$locale}/setting/password/change'
    | '/{-$locale}/setting/password/change-done'
    | '/{-$locale}/setting/payment/change'
    | '/{-$locale}/setting/payment/success'
    | '/{-$locale}/setting/profile/edit'
    | '/{-$locale}/account/reset/'
    | '/{-$locale}/account/signup/'
    | '/{-$locale}/account/withdrawal/'
    | '/{-$locale}/manage/advertise/'
    | '/{-$locale}/manage/blog/'
    | '/{-$locale}/manage/chat/'
    | '/{-$locale}/manage/comic/'
    | '/{-$locale}/manage/music/'
    | '/{-$locale}/manage/picture/'
    | '/{-$locale}/manage/video/'
    | '/{-$locale}/media/blog/'
    | '/{-$locale}/media/chat/'
    | '/{-$locale}/media/comic/'
    | '/{-$locale}/media/music/'
    | '/{-$locale}/media/picture/'
    | '/{-$locale}/media/video/'
    | '/{-$locale}/setting/mypage/'
    | '/{-$locale}/setting/payment/'
    | '/{-$locale}/setting/profile/'
    | '/{-$locale}/setting/mypage/channel/create'
    | '/{-$locale}/media/chat/$ulid/'
    | '/{-$locale}/media/chat/$ulid/thread/$messageUlid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/recommend': {
      id: '/{-$locale}/recommend'
      path: '/recommend'
      fullPath: '/{-$locale}/recommend'
      preLoaderRoute: typeof Char123LocaleChar125RecommendRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/account/login': {
      id: '/{-$locale}/account/login'
      path: '/account/login'
      fullPath: '/{-$locale}/account/login'
      preLoaderRoute: typeof Char123LocaleChar125AccountLoginRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/': {
      id: '/{-$locale}/manage/'
      path: '/manage'
      fullPath: '/{-$locale}/manage/'
      preLoaderRoute: typeof Char123LocaleChar125ManageIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/menu/channel': {
      id: '/{-$locale}/menu/channel'
      path: '/menu/channel'
      fullPath: '/{-$locale}/menu/channel'
      preLoaderRoute: typeof Char123LocaleChar125MenuChannelRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/menu/follow': {
      id: '/{-$locale}/menu/follow'
      path: '/menu/follow'
      fullPath: '/{-$locale}/menu/follow'
      preLoaderRoute: typeof Char123LocaleChar125MenuFollowRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/menu/follower': {
      id: '/{-$locale}/menu/follower'
      path: '/menu/follower'
      fullPath: '/{-$locale}/menu/follower'
      preLoaderRoute: typeof Char123LocaleChar125MenuFollowerRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/menu/knowledge': {
      id: '/{-$locale}/menu/knowledge'
      path: '/menu/knowledge'
      fullPath: '/{-$locale}/menu/knowledge'
      preLoaderRoute: typeof Char123LocaleChar125MenuKnowledgeRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/menu/userpolicy': {
      id: '/{-$locale}/menu/userpolicy'
      path: '/menu/userpolicy'
      fullPath: '/{-$locale}/menu/userpolicy'
      preLoaderRoute: typeof Char123LocaleChar125MenuUserpolicyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/notification': {
      id: '/{-$locale}/setting/notification'
      path: '/setting/notification'
      fullPath: '/{-$locale}/setting/notification'
      preLoaderRoute: typeof Char123LocaleChar125SettingNotificationRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/userpage/$ulid': {
      id: '/{-$locale}/userpage/$ulid'
      path: '/userpage/$ulid'
      fullPath: '/{-$locale}/userpage/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125UserpageUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/account/reset/': {
      id: '/{-$locale}/account/reset/'
      path: '/account/reset'
      fullPath: '/{-$locale}/account/reset/'
      preLoaderRoute: typeof Char123LocaleChar125AccountResetIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/account/reset/confirm': {
      id: '/{-$locale}/account/reset/confirm'
      path: '/account/reset/confirm'
      fullPath: '/{-$locale}/account/reset/confirm'
      preLoaderRoute: typeof Char123LocaleChar125AccountResetConfirmRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/account/reset/done': {
      id: '/{-$locale}/account/reset/done'
      path: '/account/reset/done'
      fullPath: '/{-$locale}/account/reset/done'
      preLoaderRoute: typeof Char123LocaleChar125AccountResetDoneRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/account/signup/': {
      id: '/{-$locale}/account/signup/'
      path: '/account/signup'
      fullPath: '/{-$locale}/account/signup/'
      preLoaderRoute: typeof Char123LocaleChar125AccountSignupIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/account/signup/email': {
      id: '/{-$locale}/account/signup/email'
      path: '/account/signup/email'
      fullPath: '/{-$locale}/account/signup/email'
      preLoaderRoute: typeof Char123LocaleChar125AccountSignupEmailRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/account/withdrawal/': {
      id: '/{-$locale}/account/withdrawal/'
      path: '/account/withdrawal'
      fullPath: '/{-$locale}/account/withdrawal/'
      preLoaderRoute: typeof Char123LocaleChar125AccountWithdrawalIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/account/withdrawal/confirm': {
      id: '/{-$locale}/account/withdrawal/confirm'
      path: '/account/withdrawal/confirm'
      fullPath: '/{-$locale}/account/withdrawal/confirm'
      preLoaderRoute: typeof Char123LocaleChar125AccountWithdrawalConfirmRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/advertise/': {
      id: '/{-$locale}/manage/advertise/'
      path: '/manage/advertise'
      fullPath: '/{-$locale}/manage/advertise/'
      preLoaderRoute: typeof Char123LocaleChar125ManageAdvertiseIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/advertise/$ulid': {
      id: '/{-$locale}/manage/advertise/$ulid'
      path: '/manage/advertise/$ulid'
      fullPath: '/{-$locale}/manage/advertise/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125ManageAdvertiseUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/advertise/create': {
      id: '/{-$locale}/manage/advertise/create'
      path: '/manage/advertise/create'
      fullPath: '/{-$locale}/manage/advertise/create'
      preLoaderRoute: typeof Char123LocaleChar125ManageAdvertiseCreateRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/blog/': {
      id: '/{-$locale}/manage/blog/'
      path: '/manage/blog'
      fullPath: '/{-$locale}/manage/blog/'
      preLoaderRoute: typeof Char123LocaleChar125ManageBlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/blog/$ulid': {
      id: '/{-$locale}/manage/blog/$ulid'
      path: '/manage/blog/$ulid'
      fullPath: '/{-$locale}/manage/blog/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125ManageBlogUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/blog/create': {
      id: '/{-$locale}/manage/blog/create'
      path: '/manage/blog/create'
      fullPath: '/{-$locale}/manage/blog/create'
      preLoaderRoute: typeof Char123LocaleChar125ManageBlogCreateRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/chat/': {
      id: '/{-$locale}/manage/chat/'
      path: '/manage/chat'
      fullPath: '/{-$locale}/manage/chat/'
      preLoaderRoute: typeof Char123LocaleChar125ManageChatIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/chat/$ulid': {
      id: '/{-$locale}/manage/chat/$ulid'
      path: '/manage/chat/$ulid'
      fullPath: '/{-$locale}/manage/chat/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125ManageChatUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/chat/create': {
      id: '/{-$locale}/manage/chat/create'
      path: '/manage/chat/create'
      fullPath: '/{-$locale}/manage/chat/create'
      preLoaderRoute: typeof Char123LocaleChar125ManageChatCreateRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/comic/': {
      id: '/{-$locale}/manage/comic/'
      path: '/manage/comic'
      fullPath: '/{-$locale}/manage/comic/'
      preLoaderRoute: typeof Char123LocaleChar125ManageComicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/comic/$ulid': {
      id: '/{-$locale}/manage/comic/$ulid'
      path: '/manage/comic/$ulid'
      fullPath: '/{-$locale}/manage/comic/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125ManageComicUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/comic/create': {
      id: '/{-$locale}/manage/comic/create'
      path: '/manage/comic/create'
      fullPath: '/{-$locale}/manage/comic/create'
      preLoaderRoute: typeof Char123LocaleChar125ManageComicCreateRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/music/': {
      id: '/{-$locale}/manage/music/'
      path: '/manage/music'
      fullPath: '/{-$locale}/manage/music/'
      preLoaderRoute: typeof Char123LocaleChar125ManageMusicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/music/$ulid': {
      id: '/{-$locale}/manage/music/$ulid'
      path: '/manage/music/$ulid'
      fullPath: '/{-$locale}/manage/music/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125ManageMusicUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/music/create': {
      id: '/{-$locale}/manage/music/create'
      path: '/manage/music/create'
      fullPath: '/{-$locale}/manage/music/create'
      preLoaderRoute: typeof Char123LocaleChar125ManageMusicCreateRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/picture/': {
      id: '/{-$locale}/manage/picture/'
      path: '/manage/picture'
      fullPath: '/{-$locale}/manage/picture/'
      preLoaderRoute: typeof Char123LocaleChar125ManagePictureIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/picture/$ulid': {
      id: '/{-$locale}/manage/picture/$ulid'
      path: '/manage/picture/$ulid'
      fullPath: '/{-$locale}/manage/picture/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125ManagePictureUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/picture/create': {
      id: '/{-$locale}/manage/picture/create'
      path: '/manage/picture/create'
      fullPath: '/{-$locale}/manage/picture/create'
      preLoaderRoute: typeof Char123LocaleChar125ManagePictureCreateRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/video/': {
      id: '/{-$locale}/manage/video/'
      path: '/manage/video'
      fullPath: '/{-$locale}/manage/video/'
      preLoaderRoute: typeof Char123LocaleChar125ManageVideoIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/video/$ulid': {
      id: '/{-$locale}/manage/video/$ulid'
      path: '/manage/video/$ulid'
      fullPath: '/{-$locale}/manage/video/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125ManageVideoUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/manage/video/create': {
      id: '/{-$locale}/manage/video/create'
      path: '/manage/video/create'
      fullPath: '/{-$locale}/manage/video/create'
      preLoaderRoute: typeof Char123LocaleChar125ManageVideoCreateRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/blog/': {
      id: '/{-$locale}/media/blog/'
      path: '/media/blog'
      fullPath: '/{-$locale}/media/blog/'
      preLoaderRoute: typeof Char123LocaleChar125MediaBlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/blog/$ulid': {
      id: '/{-$locale}/media/blog/$ulid'
      path: '/media/blog/$ulid'
      fullPath: '/{-$locale}/media/blog/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125MediaBlogUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/chat/': {
      id: '/{-$locale}/media/chat/'
      path: '/media/chat'
      fullPath: '/{-$locale}/media/chat/'
      preLoaderRoute: typeof Char123LocaleChar125MediaChatIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/chat/$ulid': {
      id: '/{-$locale}/media/chat/$ulid'
      path: '/media/chat/$ulid'
      fullPath: '/{-$locale}/media/chat/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125MediaChatUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/comic/': {
      id: '/{-$locale}/media/comic/'
      path: '/media/comic'
      fullPath: '/{-$locale}/media/comic/'
      preLoaderRoute: typeof Char123LocaleChar125MediaComicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/comic/$ulid': {
      id: '/{-$locale}/media/comic/$ulid'
      path: '/media/comic/$ulid'
      fullPath: '/{-$locale}/media/comic/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125MediaComicUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/music/': {
      id: '/{-$locale}/media/music/'
      path: '/media/music'
      fullPath: '/{-$locale}/media/music/'
      preLoaderRoute: typeof Char123LocaleChar125MediaMusicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/music/$ulid': {
      id: '/{-$locale}/media/music/$ulid'
      path: '/media/music/$ulid'
      fullPath: '/{-$locale}/media/music/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125MediaMusicUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/picture/': {
      id: '/{-$locale}/media/picture/'
      path: '/media/picture'
      fullPath: '/{-$locale}/media/picture/'
      preLoaderRoute: typeof Char123LocaleChar125MediaPictureIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/picture/$ulid': {
      id: '/{-$locale}/media/picture/$ulid'
      path: '/media/picture/$ulid'
      fullPath: '/{-$locale}/media/picture/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125MediaPictureUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/video/': {
      id: '/{-$locale}/media/video/'
      path: '/media/video'
      fullPath: '/{-$locale}/media/video/'
      preLoaderRoute: typeof Char123LocaleChar125MediaVideoIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/video/$ulid': {
      id: '/{-$locale}/media/video/$ulid'
      path: '/media/video/$ulid'
      fullPath: '/{-$locale}/media/video/$ulid'
      preLoaderRoute: typeof Char123LocaleChar125MediaVideoUlidRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/mypage/': {
      id: '/{-$locale}/setting/mypage/'
      path: '/setting/mypage'
      fullPath: '/{-$locale}/setting/mypage/'
      preLoaderRoute: typeof Char123LocaleChar125SettingMypageIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/mypage/edit': {
      id: '/{-$locale}/setting/mypage/edit'
      path: '/setting/mypage/edit'
      fullPath: '/{-$locale}/setting/mypage/edit'
      preLoaderRoute: typeof Char123LocaleChar125SettingMypageEditRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/password/change': {
      id: '/{-$locale}/setting/password/change'
      path: '/setting/password/change'
      fullPath: '/{-$locale}/setting/password/change'
      preLoaderRoute: typeof Char123LocaleChar125SettingPasswordChangeRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/password/change-done': {
      id: '/{-$locale}/setting/password/change-done'
      path: '/setting/password/change-done'
      fullPath: '/{-$locale}/setting/password/change-done'
      preLoaderRoute: typeof Char123LocaleChar125SettingPasswordChangeDoneRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/payment/': {
      id: '/{-$locale}/setting/payment/'
      path: '/setting/payment'
      fullPath: '/{-$locale}/setting/payment/'
      preLoaderRoute: typeof Char123LocaleChar125SettingPaymentIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/payment/change': {
      id: '/{-$locale}/setting/payment/change'
      path: '/setting/payment/change'
      fullPath: '/{-$locale}/setting/payment/change'
      preLoaderRoute: typeof Char123LocaleChar125SettingPaymentChangeRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/payment/success': {
      id: '/{-$locale}/setting/payment/success'
      path: '/setting/payment/success'
      fullPath: '/{-$locale}/setting/payment/success'
      preLoaderRoute: typeof Char123LocaleChar125SettingPaymentSuccessRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/profile/': {
      id: '/{-$locale}/setting/profile/'
      path: '/setting/profile'
      fullPath: '/{-$locale}/setting/profile/'
      preLoaderRoute: typeof Char123LocaleChar125SettingProfileIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/setting/profile/edit': {
      id: '/{-$locale}/setting/profile/edit'
      path: '/setting/profile/edit'
      fullPath: '/{-$locale}/setting/profile/edit'
      preLoaderRoute: typeof Char123LocaleChar125SettingProfileEditRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/chat/$ulid/': {
      id: '/{-$locale}/media/chat/$ulid/'
      path: '/'
      fullPath: '/{-$locale}/media/chat/$ulid/'
      preLoaderRoute: typeof Char123LocaleChar125MediaChatUlidIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MediaChatUlidRoute
    }
    '/{-$locale}/setting/mypage/channel/create': {
      id: '/{-$locale}/setting/mypage/channel/create'
      path: '/setting/mypage/channel/create'
      fullPath: '/{-$locale}/setting/mypage/channel/create'
      preLoaderRoute: typeof Char123LocaleChar125SettingMypageChannelCreateRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/media/chat/$ulid/thread/$messageUlid': {
      id: '/{-$locale}/media/chat/$ulid/thread/$messageUlid'
      path: '/thread/$messageUlid'
      fullPath: '/{-$locale}/media/chat/$ulid/thread/$messageUlid'
      preLoaderRoute: typeof Char123LocaleChar125MediaChatUlidThreadMessageUlidRouteImport
      parentRoute: typeof Char123LocaleChar125MediaChatUlidRoute
    }
  }
}

interface Char123LocaleChar125MediaChatUlidRouteChildren {
  Char123LocaleChar125MediaChatUlidIndexRoute: typeof Char123LocaleChar125MediaChatUlidIndexRoute
  Char123LocaleChar125MediaChatUlidThreadMessageUlidRoute: typeof Char123LocaleChar125MediaChatUlidThreadMessageUlidRoute
}

const Char123LocaleChar125MediaChatUlidRouteChildren: Char123LocaleChar125MediaChatUlidRouteChildren =
  {
    Char123LocaleChar125MediaChatUlidIndexRoute:
      Char123LocaleChar125MediaChatUlidIndexRoute,
    Char123LocaleChar125MediaChatUlidThreadMessageUlidRoute:
      Char123LocaleChar125MediaChatUlidThreadMessageUlidRoute,
  }

const Char123LocaleChar125MediaChatUlidRouteWithChildren =
  Char123LocaleChar125MediaChatUlidRoute._addFileChildren(
    Char123LocaleChar125MediaChatUlidRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125RecommendRoute: typeof Char123LocaleChar125RecommendRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125AccountLoginRoute: typeof Char123LocaleChar125AccountLoginRoute
  Char123LocaleChar125MenuChannelRoute: typeof Char123LocaleChar125MenuChannelRoute
  Char123LocaleChar125MenuFollowRoute: typeof Char123LocaleChar125MenuFollowRoute
  Char123LocaleChar125MenuFollowerRoute: typeof Char123LocaleChar125MenuFollowerRoute
  Char123LocaleChar125MenuKnowledgeRoute: typeof Char123LocaleChar125MenuKnowledgeRoute
  Char123LocaleChar125MenuUserpolicyRoute: typeof Char123LocaleChar125MenuUserpolicyRoute
  Char123LocaleChar125SettingNotificationRoute: typeof Char123LocaleChar125SettingNotificationRoute
  Char123LocaleChar125UserpageUlidRoute: typeof Char123LocaleChar125UserpageUlidRoute
  Char123LocaleChar125ManageIndexRoute: typeof Char123LocaleChar125ManageIndexRoute
  Char123LocaleChar125AccountResetConfirmRoute: typeof Char123LocaleChar125AccountResetConfirmRoute
  Char123LocaleChar125AccountResetDoneRoute: typeof Char123LocaleChar125AccountResetDoneRoute
  Char123LocaleChar125AccountSignupEmailRoute: typeof Char123LocaleChar125AccountSignupEmailRoute
  Char123LocaleChar125AccountWithdrawalConfirmRoute: typeof Char123LocaleChar125AccountWithdrawalConfirmRoute
  Char123LocaleChar125ManageAdvertiseUlidRoute: typeof Char123LocaleChar125ManageAdvertiseUlidRoute
  Char123LocaleChar125ManageAdvertiseCreateRoute: typeof Char123LocaleChar125ManageAdvertiseCreateRoute
  Char123LocaleChar125ManageBlogUlidRoute: typeof Char123LocaleChar125ManageBlogUlidRoute
  Char123LocaleChar125ManageBlogCreateRoute: typeof Char123LocaleChar125ManageBlogCreateRoute
  Char123LocaleChar125ManageChatUlidRoute: typeof Char123LocaleChar125ManageChatUlidRoute
  Char123LocaleChar125ManageChatCreateRoute: typeof Char123LocaleChar125ManageChatCreateRoute
  Char123LocaleChar125ManageComicUlidRoute: typeof Char123LocaleChar125ManageComicUlidRoute
  Char123LocaleChar125ManageComicCreateRoute: typeof Char123LocaleChar125ManageComicCreateRoute
  Char123LocaleChar125ManageMusicUlidRoute: typeof Char123LocaleChar125ManageMusicUlidRoute
  Char123LocaleChar125ManageMusicCreateRoute: typeof Char123LocaleChar125ManageMusicCreateRoute
  Char123LocaleChar125ManagePictureUlidRoute: typeof Char123LocaleChar125ManagePictureUlidRoute
  Char123LocaleChar125ManagePictureCreateRoute: typeof Char123LocaleChar125ManagePictureCreateRoute
  Char123LocaleChar125ManageVideoUlidRoute: typeof Char123LocaleChar125ManageVideoUlidRoute
  Char123LocaleChar125ManageVideoCreateRoute: typeof Char123LocaleChar125ManageVideoCreateRoute
  Char123LocaleChar125MediaBlogUlidRoute: typeof Char123LocaleChar125MediaBlogUlidRoute
  Char123LocaleChar125MediaChatUlidRoute: typeof Char123LocaleChar125MediaChatUlidRouteWithChildren
  Char123LocaleChar125MediaComicUlidRoute: typeof Char123LocaleChar125MediaComicUlidRoute
  Char123LocaleChar125MediaMusicUlidRoute: typeof Char123LocaleChar125MediaMusicUlidRoute
  Char123LocaleChar125MediaPictureUlidRoute: typeof Char123LocaleChar125MediaPictureUlidRoute
  Char123LocaleChar125MediaVideoUlidRoute: typeof Char123LocaleChar125MediaVideoUlidRoute
  Char123LocaleChar125SettingMypageEditRoute: typeof Char123LocaleChar125SettingMypageEditRoute
  Char123LocaleChar125SettingPasswordChangeRoute: typeof Char123LocaleChar125SettingPasswordChangeRoute
  Char123LocaleChar125SettingPasswordChangeDoneRoute: typeof Char123LocaleChar125SettingPasswordChangeDoneRoute
  Char123LocaleChar125SettingPaymentChangeRoute: typeof Char123LocaleChar125SettingPaymentChangeRoute
  Char123LocaleChar125SettingPaymentSuccessRoute: typeof Char123LocaleChar125SettingPaymentSuccessRoute
  Char123LocaleChar125SettingProfileEditRoute: typeof Char123LocaleChar125SettingProfileEditRoute
  Char123LocaleChar125AccountResetIndexRoute: typeof Char123LocaleChar125AccountResetIndexRoute
  Char123LocaleChar125AccountSignupIndexRoute: typeof Char123LocaleChar125AccountSignupIndexRoute
  Char123LocaleChar125AccountWithdrawalIndexRoute: typeof Char123LocaleChar125AccountWithdrawalIndexRoute
  Char123LocaleChar125ManageAdvertiseIndexRoute: typeof Char123LocaleChar125ManageAdvertiseIndexRoute
  Char123LocaleChar125ManageBlogIndexRoute: typeof Char123LocaleChar125ManageBlogIndexRoute
  Char123LocaleChar125ManageChatIndexRoute: typeof Char123LocaleChar125ManageChatIndexRoute
  Char123LocaleChar125ManageComicIndexRoute: typeof Char123LocaleChar125ManageComicIndexRoute
  Char123LocaleChar125ManageMusicIndexRoute: typeof Char123LocaleChar125ManageMusicIndexRoute
  Char123LocaleChar125ManagePictureIndexRoute: typeof Char123LocaleChar125ManagePictureIndexRoute
  Char123LocaleChar125ManageVideoIndexRoute: typeof Char123LocaleChar125ManageVideoIndexRoute
  Char123LocaleChar125MediaBlogIndexRoute: typeof Char123LocaleChar125MediaBlogIndexRoute
  Char123LocaleChar125MediaChatIndexRoute: typeof Char123LocaleChar125MediaChatIndexRoute
  Char123LocaleChar125MediaComicIndexRoute: typeof Char123LocaleChar125MediaComicIndexRoute
  Char123LocaleChar125MediaMusicIndexRoute: typeof Char123LocaleChar125MediaMusicIndexRoute
  Char123LocaleChar125MediaPictureIndexRoute: typeof Char123LocaleChar125MediaPictureIndexRoute
  Char123LocaleChar125MediaVideoIndexRoute: typeof Char123LocaleChar125MediaVideoIndexRoute
  Char123LocaleChar125SettingMypageIndexRoute: typeof Char123LocaleChar125SettingMypageIndexRoute
  Char123LocaleChar125SettingPaymentIndexRoute: typeof Char123LocaleChar125SettingPaymentIndexRoute
  Char123LocaleChar125SettingProfileIndexRoute: typeof Char123LocaleChar125SettingProfileIndexRoute
  Char123LocaleChar125SettingMypageChannelCreateRoute: typeof Char123LocaleChar125SettingMypageChannelCreateRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125RecommendRoute: Char123LocaleChar125RecommendRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125AccountLoginRoute:
      Char123LocaleChar125AccountLoginRoute,
    Char123LocaleChar125MenuChannelRoute: Char123LocaleChar125MenuChannelRoute,
    Char123LocaleChar125MenuFollowRoute: Char123LocaleChar125MenuFollowRoute,
    Char123LocaleChar125MenuFollowerRoute:
      Char123LocaleChar125MenuFollowerRoute,
    Char123LocaleChar125MenuKnowledgeRoute:
      Char123LocaleChar125MenuKnowledgeRoute,
    Char123LocaleChar125MenuUserpolicyRoute:
      Char123LocaleChar125MenuUserpolicyRoute,
    Char123LocaleChar125SettingNotificationRoute:
      Char123LocaleChar125SettingNotificationRoute,
    Char123LocaleChar125UserpageUlidRoute:
      Char123LocaleChar125UserpageUlidRoute,
    Char123LocaleChar125ManageIndexRoute: Char123LocaleChar125ManageIndexRoute,
    Char123LocaleChar125AccountResetConfirmRoute:
      Char123LocaleChar125AccountResetConfirmRoute,
    Char123LocaleChar125AccountResetDoneRoute:
      Char123LocaleChar125AccountResetDoneRoute,
    Char123LocaleChar125AccountSignupEmailRoute:
      Char123LocaleChar125AccountSignupEmailRoute,
    Char123LocaleChar125AccountWithdrawalConfirmRoute:
      Char123LocaleChar125AccountWithdrawalConfirmRoute,
    Char123LocaleChar125ManageAdvertiseUlidRoute:
      Char123LocaleChar125ManageAdvertiseUlidRoute,
    Char123LocaleChar125ManageAdvertiseCreateRoute:
      Char123LocaleChar125ManageAdvertiseCreateRoute,
    Char123LocaleChar125ManageBlogUlidRoute:
      Char123LocaleChar125ManageBlogUlidRoute,
    Char123LocaleChar125ManageBlogCreateRoute:
      Char123LocaleChar125ManageBlogCreateRoute,
    Char123LocaleChar125ManageChatUlidRoute:
      Char123LocaleChar125ManageChatUlidRoute,
    Char123LocaleChar125ManageChatCreateRoute:
      Char123LocaleChar125ManageChatCreateRoute,
    Char123LocaleChar125ManageComicUlidRoute:
      Char123LocaleChar125ManageComicUlidRoute,
    Char123LocaleChar125ManageComicCreateRoute:
      Char123LocaleChar125ManageComicCreateRoute,
    Char123LocaleChar125ManageMusicUlidRoute:
      Char123LocaleChar125ManageMusicUlidRoute,
    Char123LocaleChar125ManageMusicCreateRoute:
      Char123LocaleChar125ManageMusicCreateRoute,
    Char123LocaleChar125ManagePictureUlidRoute:
      Char123LocaleChar125ManagePictureUlidRoute,
    Char123LocaleChar125ManagePictureCreateRoute:
      Char123LocaleChar125ManagePictureCreateRoute,
    Char123LocaleChar125ManageVideoUlidRoute:
      Char123LocaleChar125ManageVideoUlidRoute,
    Char123LocaleChar125ManageVideoCreateRoute:
      Char123LocaleChar125ManageVideoCreateRoute,
    Char123LocaleChar125MediaBlogUlidRoute:
      Char123LocaleChar125MediaBlogUlidRoute,
    Char123LocaleChar125MediaChatUlidRoute:
      Char123LocaleChar125MediaChatUlidRouteWithChildren,
    Char123LocaleChar125MediaComicUlidRoute:
      Char123LocaleChar125MediaComicUlidRoute,
    Char123LocaleChar125MediaMusicUlidRoute:
      Char123LocaleChar125MediaMusicUlidRoute,
    Char123LocaleChar125MediaPictureUlidRoute:
      Char123LocaleChar125MediaPictureUlidRoute,
    Char123LocaleChar125MediaVideoUlidRoute:
      Char123LocaleChar125MediaVideoUlidRoute,
    Char123LocaleChar125SettingMypageEditRoute:
      Char123LocaleChar125SettingMypageEditRoute,
    Char123LocaleChar125SettingPasswordChangeRoute:
      Char123LocaleChar125SettingPasswordChangeRoute,
    Char123LocaleChar125SettingPasswordChangeDoneRoute:
      Char123LocaleChar125SettingPasswordChangeDoneRoute,
    Char123LocaleChar125SettingPaymentChangeRoute:
      Char123LocaleChar125SettingPaymentChangeRoute,
    Char123LocaleChar125SettingPaymentSuccessRoute:
      Char123LocaleChar125SettingPaymentSuccessRoute,
    Char123LocaleChar125SettingProfileEditRoute:
      Char123LocaleChar125SettingProfileEditRoute,
    Char123LocaleChar125AccountResetIndexRoute:
      Char123LocaleChar125AccountResetIndexRoute,
    Char123LocaleChar125AccountSignupIndexRoute:
      Char123LocaleChar125AccountSignupIndexRoute,
    Char123LocaleChar125AccountWithdrawalIndexRoute:
      Char123LocaleChar125AccountWithdrawalIndexRoute,
    Char123LocaleChar125ManageAdvertiseIndexRoute:
      Char123LocaleChar125ManageAdvertiseIndexRoute,
    Char123LocaleChar125ManageBlogIndexRoute:
      Char123LocaleChar125ManageBlogIndexRoute,
    Char123LocaleChar125ManageChatIndexRoute:
      Char123LocaleChar125ManageChatIndexRoute,
    Char123LocaleChar125ManageComicIndexRoute:
      Char123LocaleChar125ManageComicIndexRoute,
    Char123LocaleChar125ManageMusicIndexRoute:
      Char123LocaleChar125ManageMusicIndexRoute,
    Char123LocaleChar125ManagePictureIndexRoute:
      Char123LocaleChar125ManagePictureIndexRoute,
    Char123LocaleChar125ManageVideoIndexRoute:
      Char123LocaleChar125ManageVideoIndexRoute,
    Char123LocaleChar125MediaBlogIndexRoute:
      Char123LocaleChar125MediaBlogIndexRoute,
    Char123LocaleChar125MediaChatIndexRoute:
      Char123LocaleChar125MediaChatIndexRoute,
    Char123LocaleChar125MediaComicIndexRoute:
      Char123LocaleChar125MediaComicIndexRoute,
    Char123LocaleChar125MediaMusicIndexRoute:
      Char123LocaleChar125MediaMusicIndexRoute,
    Char123LocaleChar125MediaPictureIndexRoute:
      Char123LocaleChar125MediaPictureIndexRoute,
    Char123LocaleChar125MediaVideoIndexRoute:
      Char123LocaleChar125MediaVideoIndexRoute,
    Char123LocaleChar125SettingMypageIndexRoute:
      Char123LocaleChar125SettingMypageIndexRoute,
    Char123LocaleChar125SettingPaymentIndexRoute:
      Char123LocaleChar125SettingPaymentIndexRoute,
    Char123LocaleChar125SettingProfileIndexRoute:
      Char123LocaleChar125SettingProfileIndexRoute,
    Char123LocaleChar125SettingMypageChannelCreateRoute:
      Char123LocaleChar125SettingMypageChannelCreateRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
